server:
  port: 8080

eureka:
  port: 8761
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.ip-address:localhost}:${eureka.port:8761}/eureka/
    registerWithEureka: true
    fetchRegistry: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: search-place-service
        uri: lb://SEARCH-PLACE-SERVICE
        predicates:
        - Path=/search/**
      - id: keyword-rank-service
        uri: lb://KEYWORD-RANK-SERVICE
        predicates:
        - Path=/keyword/**        
logging:
  file:
    name: api-gateway.log
    path: ./data/logs  